### ISSUE TITLE
StrongSwan builds with VPP version 18.10.0-release

### ISSUE THREAD

**Issue by mestery** [mestery/vpp-container-fun#17]
It fails as follows:

```
make[5]: Entering directory `/strongswan/src/libcharon/plugins/kernel_vpp'
depbase=`echo kernel_vpp_plugin.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||'`;\
/bin/sh ../../../../libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I../../../..  -I../../../../src/include -I../../../../src/libstrongswan -I../../../../src/libcharon  -rdynamic -g -O2 -Wall -Wno-format -Wno-format-security -Wno-pointer-sign -include /strongswan/config.h -MT kernel_vpp_plugin.lo -MD -MP -MF $depbase.Tpo -c -o kernel_vpp_plugin.lo kernel_vpp_plugin.c &&\
mv -f $depbase.Tpo $depbase.Plo
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I../../../.. -I../../../../src/include -I../../../../src/libstrongswan -I../../../../src/libcharon -rdynamic -g -O2 -Wall -Wno-format -Wno-format-security -Wno-pointer-sign -include /strongswan/config.h -MT kernel_vpp_plugin.lo -MD -MP -MF .deps/kernel_vpp_plugin.Tpo -c kernel_vpp_plugin.c  -fPIC -DPIC -o .libs/kernel_vpp_plugin.o
In file included from /usr/include/vppinfra/mem.h:51:0,
                 from /usr/include/vppinfra/vec.h:42,
                 from /usr/include/vppinfra/error.h:53,
                 from /usr/include/vlibapi/api.h:24,
                 from kernel_vpp_plugin.c:2:
../../../../src/libstrongswan/resolver/resolver_response.h:51:2: error: expected identifier before numeric constant
  INSECURE,
  ^
make[5]: Leaving directory `/strongswan/src/libcharon/plugins/kernel_vpp'
make[5]: *** [kernel_vpp_plugin.lo] Error 1
make[4]: *** [all-recursive] Error 1
make[4]: Leaving directory `/strongswan/src/libcharon'
make[3]: *** [all] Error 2
make[3]: Leaving directory `/strongswan/src/libcharon'
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory `/strongswan/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/strongswan'
make: *** [all] Error 2
```

**Comment by mestery** [comment]
This was fixed.
